---
version: '3.3'

services:

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - ./cassandra/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      kafka_net:
        ipv4_address: 172.22.0.6

networks:
  kafka_net:
    external:
      name: kafka_net
