apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-readside-cluster
  labels:
    release: prometheus
    app: readside-cluster
spec:
  selector:
    matchLabels:
      app: readside-cluster
  # namespaceSelector:
  #   matchNames:
  #     - copernico
  endpoints:
    - port: monitoring
