---
#headless
apiVersion: v1
kind: Service
metadata:
  name: application-dns-internal
  namespace: copernico
spec:
  ports:
    - name: management
      port: 8559
      protocol: TCP
      targetPort: 8559
    - name: remoting
      port: 2554
      protocol: TCP
      targetPort: 2554
  selector:
    app: readside-cluster
  clusterIP: None
  publishNotReadyAddresses: true
#headless
---
#public
kind: Service
apiVersion: v1
metadata:
  name: readside-cluster
  namespace: copernico
spec:
  type: NodePort
  selector:
    app: readside-cluster
  ports:  
    - protocol: TCP
      name: api
      port: 8082
      targetPort: api
#public
---
