apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-pcs-cluster
  labels:
    release: prometheus
    app: pcs-cluster
spec:
  selector:
    matchLabels:
      app: pcs-cluster
  endpoints:
    - port: monitoring
