---
#headless
apiVersion: v1
kind: Service
metadata:
  name: application-dns-internal
  namespace: copernico
spec:
  ports:
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
    - name: remoting
      port: 2551
      protocol: TCP
      targetPort: 2551
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: monitoring
  selector:
    app: pcs-cluster
  clusterIP: None
  publishNotReadyAddresses: true
#headless
---
#public
kind: Service
apiVersion: v1
metadata:
  name: pcs-cluster
  namespace: copernico
spec:
  type: NodePort
  selector:
    app: pcs-cluster
  ports:  
    - protocol: TCP
      name: api
      port: 8081
      targetPort: api
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: monitoring
#public
---
