---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: copernico
  labels:
    app: cassandra
spec:
  type: ClusterIP
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
