{
 "title": "DGR-COP-SUJETO_TRI",
 "time": { "from": "2020-08-07T21:48:39.618Z", "to": "2020-08-07T21:55:29.074Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe \nsrc=\"http://0.0.0.0:8000/monitor.html\"\n width=\"100%\"\n  height=\"900px\" \n  frameBorder=\"0\"/>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 8, "y": 24 }, "options": { "content": "# writeside\n\n" } },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 15, "y": 24 }, "options": { "content": "# readside\n\n" } },
  {
   "title": "Kafka consumptions per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum(\nincrease(counters_total{entity=\"actor-transaction-sujeto_tributario_transaction-request\"}[1m])\n)\n"
    }
   ]
  },
  {
   "title": "Cassandra projections per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\nsum(\nincrease(counters_total{entity=\"projection-handler-sujeto_projection_handler-request\"}[1m])\n)\n"
    }
   ]
  },
  {
   "title": "latencia akka",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nhistogram_quantile(0.9, \n  rate(histograms_bucket{entity=\"actor-transaction-sujeto_tributario_transaction-latency\"}[5m])\n)\n",
     "legendFormat": "actor-transaction-_obligacion_tributaria_transaction-latency"
    }
   ]
  },
  {
   "title": "latencia cassandra",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histograms_bucket{le=\"3000.0\",entity=\"projection-handler-sujeto_projection_handler-latency\"}",
     "legendFormat": "actor-transaction-_obligacion_tributaria_transaction-latency"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTIONS ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(counters_total{entity=\"actor-transaction-sujeto_tributario_transaction-request\"} )\n"
    }
   ]
  },
  {
   "title": "TOTAL PROJECTIONS ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(counters_total{entity=\"projection-handler-sujeto_projection_handler-request\"} )"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTIONS PER NODE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "counters_total{entity=\"actor-transaction-sujeto_tributario_transaction-request\"} \n"
    }
   ]
  },
  {
   "title": "TOTAL PROJECTIONS PER NODE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "counters_total{entity=\"projection-handler-sujeto_projection_handler-request\"} "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 7, "x": 9, "y": 48 }, "options": { "content": "# published events\n\n\n" } },
  {
   "title": "PERSISTENCIAS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "counters_total{entity=\"SujetoActor-persisted-SujetoSnapshotPersisted\"} "
    }
   ]
  }
 ]
}